# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: email.proto
# Protobuf Python Version: 6.33.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    0,
    '',
    'email.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x65mail.proto\x12\x05\x65mail\"\xe4\x01\n\nEmailEvent\x12\x10\n\x08\x65vent_id\x18\x01 \x01(\t\x12\x1e\n\x04type\x18\x02 \x01(\x0e\x32\x10.email.EmailType\x12\x11\n\trecipient\x18\x03 \x01(\t\x12)\n\x04\x64\x61ta\x18\x04 \x03(\x0b\x32\x1b.email.EmailEvent.DataEntry\x12&\n\x0b\x61ttachments\x18\x05 \x03(\x0b\x32\x11.email.Attachment\x12\x11\n\ttimestamp\x18\x06 \x01(\x03\x1a+\n\tDataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"B\n\nAttachment\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\x12\x14\n\x0c\x63ontent_type\x18\x02 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x03 \x01(\x0c*\xeb\x01\n\tEmailType\x12\x16\n\x12\x41\x43\x43OUNT_ACTIVATION\x10\x00\x12\x12\n\x0ePASSWORD_RESET\x10\x01\x12\x16\n\x12\x45MAIL_VERIFICATION\x10\x02\x12\x14\n\x10\x41\x43\x43OUNT_DELETION\x10\x03\x12\x14\n\x10PASSWORD_CHANGED\x10\x04\x12\x15\n\x11INVOICE_GENERATED\x10\x05\x12\x15\n\x11PAYMENT_CONFIRMED\x10\x06\x12\x12\n\x0ePAYMENT_FAILED\x10\x07\x12\x13\n\x0fTEAM_INVITATION\x10\x08\x12\x17\n\x13\x41LERT_TRIAGE_REPORT\x10\tB2Z0github.com/aifaniyi/resyze-proto/proto/generatedb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'email_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z0github.com/aifaniyi/resyze-proto/proto/generated'
  _globals['_EMAILEVENT_DATAENTRY']._loaded_options = None
  _globals['_EMAILEVENT_DATAENTRY']._serialized_options = b'8\001'
  _globals['_EMAILTYPE']._serialized_start=322
  _globals['_EMAILTYPE']._serialized_end=557
  _globals['_EMAILEVENT']._serialized_start=23
  _globals['_EMAILEVENT']._serialized_end=251
  _globals['_EMAILEVENT_DATAENTRY']._serialized_start=208
  _globals['_EMAILEVENT_DATAENTRY']._serialized_end=251
  _globals['_ATTACHMENT']._serialized_start=253
  _globals['_ATTACHMENT']._serialized_end=319
# @@protoc_insertion_point(module_scope)
